name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose an environment to deploy to: <dev|staging|prod>"
        required: true
        default: "prod"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - run: echo "PACKAGE_JSON=$(jq -c . < package.json)" >> $GITHUB_ENV
      - uses: pnpm/action-setup@v4
        with:
            version: ${{ fromJson(env.PACKAGE_JSON).volta.pnpm }}
      - uses: actions/setup-node@v3
        with:
            node-version: ${{ fromJson(env.PACKAGE_JSON).volta.node }}
            registry-url: https://registry.npmjs.org/
      - run: pnpm --filter=@skyline/worker install
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          packageManager: pnpm
          workingDirectory: ./packages/worker
          command: deploy --env ${{ github.event.inputs.environment || 'prod' }}